<?php

// Generated by barryvdh/laravel-ide-helper. Do not edit.
// This file is consumed as a passive data source by laravel-lsp.

namespace App\Models {

    /**
     * App\Models\User
     *
     * @property int $id
     * @property string $email_address
     * @property string $first_name
     * @property \Carbon\Carbon|null $email_verified_at
     * @property \Carbon\Carbon $created_at
     * @property \Carbon\Carbon $updated_at
     * @property-read int|null $roles_count
     * @method static \Illuminate\Database\Eloquent\Builder active()
     * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
     */
    class User extends \Eloquent {}
}
